name = "paranjapeblueridge"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
NEXT_PUBLIC_ADMIN_PIN = "1925"

# Ultra-Advanced Cloudflare Edge Caching & Rule Directives
[env.production]
name = "paranjapeblueridge-production"
routes = [
  { pattern = "paranjapeblueridge.com/*", zone_name = "paranjapeblueridge.com" },
  { pattern = "www.paranjapeblueridge.com/*", zone_name = "paranjapeblueridge.com" }
]
