// AUTO-GENERATED BY SCRAPER
import { Project } from './master-data';

export const extendedProjects: Project[] = [
  {
    "id": "forest-trails",
    "slug": "paranjape-forest-trails-bhugaon-pune",
    "name": "Forest Trails",
    "tagline": "170-Acre Premium Township in Bhugaon",
    "taglineMr": "भूगाव मधील १७० एकरची प्रीमियम टाउनशिप",
    "description": "Forest Trails is an exclusive 170-acre gated township in Bhugaon, offering premium villas, bungalows, and high-rise apartments nestled amidst nature. It features an operational equestrian center, the Cliff school, and unparalleled views of the Sahyadri hills, making it the most coveted address just minutes away from Kothrud and Bavdhan.",
    "descriptionMr": "फॉरेस्ट ट्रेल्स ही भूगाव मधील एक १७० एकरची खास टाउनशिप आहे, जिथे प्रीमियम व्हिला आणि उंच इमारती निसर्गाच्या सानिध्यात आहेत.",
    "carpetArea": "1,200 - 4,500 Sq. Ft.",
    "price": "₹ 1.25 Cr onwards",
    "priceValue": 12500000,
    "storeys": 15,
    "possession": "Ready & Under Construction",
    "reraNumber": "P52100024251",
    "geo": {
      "latitude": 18.4988,
      "longitude": 73.7431
    },
    "usp": [
      "170-Acre Nature Integrated Township",
      "Operational Equestrian Center",
      "The Cliff School Inside Campus",
      "Minutes from Kothrud"
    ],
    "specs": [
      {
        "title": "Design",
        "items": [
          "Eco-friendly Architecture",
          "Expansive Private Gardens for Villas"
        ]
      }
    ],
    "amenities": [
      "Equestrian Center",
      "Lifestyle Club House",
      "Nature Trails & Trekking Paths",
      "Premium Retail Outlets"
    ],
    "configurations": [
      {
        "slug": "luxury-villas",
        "title": "Luxury Villas",
        "titleMr": "लक्झरी व्हिला",
        "carpetArea": "3,500 Sq. Ft.",
        "price": "₹ 4.50 Cr*",
        "priceValue": 45000000,
        "numberOfRooms": 4,
        "floorSizeSqFt": 3500,
        "image": "/assets/images/township-day.jpg"
      },
      {
        "slug": "2-bhk-apartments",
        "title": "2 BHK Nature Apartments",
        "titleMr": "२ बीएचके अपार्टमेंट्स",
        "carpetArea": "1,200 Sq. Ft.",
        "price": "₹ 1.25 Cr*",
        "priceValue": 12500000,
        "numberOfRooms": 2,
        "floorSizeSqFt": 1200,
        "image": "/assets/images/township-day.jpg"
      }
    ]
  },
  {
    "id": "athashri-baner",
    "slug": "paranjape-athashri-baner-pune",
    "name": "Athashri Baner",
    "tagline": "India's Pioneer in Senior Citizen Housing",
    "taglineMr": "ज्येष्ठ नागरिक गृहनिर्माणात भारतातील अग्रणी",
    "description": "Athashri Baner by Paranjape Schemes is a pioneering senior citizen housing project. Designed exclusively for the elderly, it provides a safe, engaging, and dignified lifestyle with 24/7 medical assistance, wheelchair-friendly design, and a vibrant community of like-minded seniors.",
    "descriptionMr": "परंजपे स्कीम्सचे अथाश्री बाणेर हा ज्येष्ठ नागरिकांसाठी खास डिझाइन केलेला एक अनोखा गृहनिर्माण प्रकल्प आहे, जिथे २४/७ वैद्यकीय मदत उपलब्ध आहे.",
    "carpetArea": "650 - 950 Sq. Ft.",
    "price": "₹ 85 L onwards",
    "priceValue": 8500000,
    "storeys": 11,
    "possession": "Ready Possession",
    "reraNumber": "P52100000001",
    "geo": {
      "latitude": 18.559,
      "longitude": 73.7868
    },
    "usp": [
      "24/7 Resident Doctor & Ambulance",
      "Anti-skid Flooring & Grab Bars",
      "Vibrant Senior Community",
      "Daily Meals & Housekeeping Services"
    ],
    "specs": [
      {
        "title": "Senior-Friendly",
        "items": [
          "Wheelchair Accessible Corridors",
          "Emergency Pull Cords in Bathrooms"
        ]
      }
    ],
    "amenities": [
      "Doctor on Call",
      "Community Dining Hall",
      "Library & Reading Room",
      "Shuttle Service"
    ],
    "configurations": [
      {
        "slug": "1-bhk-senior-living",
        "title": "1 BHK Senior Living",
        "titleMr": "१ बीएचके ज्येष्ठ निवास",
        "carpetArea": "650 Sq. Ft.",
        "price": "₹ 85 L*",
        "priceValue": 8500000,
        "numberOfRooms": 1,
        "floorSizeSqFt": 650,
        "image": "/assets/images/township-day.jpg"
      },
      {
        "slug": "2-bhk-senior-living",
        "title": "2 BHK Senior Living",
        "titleMr": "२ बीएचके ज्येष्ठ निवास",
        "carpetArea": "950 Sq. Ft.",
        "price": "₹ 1.15 Cr*",
        "priceValue": 11500000,
        "numberOfRooms": 2,
        "floorSizeSqFt": 950,
        "image": "/assets/images/township-day.jpg"
      }
    ]
  },
  {
    "id": "skyone",
    "slug": "paranjape-sky-one-model-colony-pune",
    "name": "Sky One",
    "tagline": "Ultra-Luxury Residences in Model Colony",
    "taglineMr": "मॉडेल कॉलनीतील अल्ट्रा-लक्झरी निवास",
    "description": "Sky One is the epitome of ultra-luxury living in Model Colony, Pune. This exclusive single-tower development features expansive 4 BHK and 5 BHK sky villas, offering uncompromised privacy, panoramic views of the city, and unparalleled bespoke amenities for the elite.",
    "descriptionMr": "स्काय वन हे पुण्यातील मॉडेल कॉलनीमध्ये अत्यंत आलिशान राहणीमानाचे प्रतीक आहे. यात ४ बीएचके आणि ५ बीएचके स्काय व्हिला आहेत.",
    "carpetArea": "3,500 - 5,000 Sq. Ft.",
    "price": "₹ 6.5 Cr onwards",
    "priceValue": 65000000,
    "storeys": 21,
    "possession": "Ready Possession",
    "reraNumber": "P52100000002",
    "geo": {
      "latitude": 18.5332,
      "longitude": 73.8322
    },
    "usp": [
      "Located in Prestigious Model Colony",
      "One Residence per Floor",
      "Private Swimming Pools",
      "Panoramic City Views"
    ],
    "specs": [
      {
        "title": "Luxury",
        "items": [
          "Italian Marble Flooring",
          "Smart Home Automation",
          "Private Elevators"
        ]
      }
    ],
    "amenities": [
      "Rooftop Infinity Pool",
      "Exclusive Concierge",
      "Private Gym",
      "Chauffeur Lounges"
    ],
    "configurations": [
      {
        "slug": "4-bhk-sky-villa",
        "title": "4 BHK Sky Villa",
        "titleMr": "४ बीएचके स्काय व्हिला",
        "carpetArea": "3,500 Sq. Ft.",
        "price": "₹ 6.5 Cr*",
        "priceValue": 65000000,
        "numberOfRooms": 4,
        "floorSizeSqFt": 3500,
        "image": "/assets/images/township-day.jpg"
      },
      {
        "slug": "5-bhk-penthouse",
        "title": "5 BHK Penthouse",
        "titleMr": "५ बीएचके पेंटहाऊस",
        "carpetArea": "5,000 Sq. Ft.",
        "price": "₹ 9.5 Cr*",
        "priceValue": 95000000,
        "numberOfRooms": 5,
        "floorSizeSqFt": 5000,
        "image": "/assets/images/township-day.jpg"
      }
    ]
  }
];
